# Generated by Django 5.2.6 on 2026-01-29 14:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import fernet_fields.fields
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('UGX', 'Ugandan Shilling'), ('TZS', 'Tanzanian Shilling')], default='KES', max_length=3)),
                ('balance_cache', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('version', models.PositiveIntegerField(default=1)),
                ('data_residency', models.CharField(choices=[('KENYA', 'Kenya'), ('EU', 'European Union'), ('US', 'United States'), ('GLOBAL', 'Global')], default='KENYA', max_length=10)),
                ('consent_required', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'core_group',
                'indexes': [models.Index(fields=['name'], name='core_group_name_9ccf81_idx'), models.Index(fields=['created_at'], name='core_group_created_332669_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('balance_cache__gte', 0)), name='positive_balance')],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('TREASURER', 'Treasurer'), ('MEMBER', 'Member')], default='MEMBER', max_length=12)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='core.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_membership',
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('CONTRIBUTION', 'Contribution'), ('EXPENSE', 'Expense'), ('PENALTY', 'Penalty'), ('DIVIDEND', 'Dividend'), ('LOAN', 'Loan'), ('LOAN_REPAYMENT', 'Loan Repayment'), ('INTEREST', 'Interest'), ('OTHER', 'Other')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('contribution_category', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ledger_entries/%Y/%m/')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('hash_prev_tx', models.CharField(blank=True, max_length=64, null=True)),
                ('is_reversal', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='core.group')),
                ('reversed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversals', to='core.ledgerentry')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='core.membership')),
            ],
            options={
                'db_table': 'core_ledgerentry',
                'ordering': ['-occurred_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', fernet_fields.fields.EncryptedCharField(blank=True, max_length=150)),
                ('phone_country_code', fernet_fields.fields.EncryptedCharField(blank=True, max_length=5)),
                ('phone_number', fernet_fields.fields.EncryptedCharField(blank=True, max_length=30)),
                ('has_seen_instructions', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_profile',
            },
        ),
        migrations.CreateModel(
            name='TransactionHash',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hash_value', models.CharField(max_length=64)),
                ('hash_prev_tx', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_hash', to='core.ledgerentry')),
            ],
            options={
                'db_table': 'core_transactionhash',
            },
        ),
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('purpose', models.CharField(choices=[('WHATSAPP_NOTIFICATION', 'WhatsApp Notification'), ('EMAIL_MARKETING', 'Email Marketing'), ('THIRD_PARTY_SHARING', 'Third Party Sharing'), ('ANALYTICS', 'Analytics')], max_length=50)),
                ('granted', models.BooleanField(default=False)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('consent_text', models.TextField()),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_consentrecord',
                'indexes': [models.Index(fields=['user', 'purpose'], name='core_consen_user_id_6234b1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True)), fields=('user', 'purpose'), name='unique_active_consent')],
            },
        ),
        migrations.CreateModel(
            name='EventStore',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('FINANCIAL_EVENT', 'Financial Event'), ('MEMBERSHIP_EVENT', 'Membership Event'), ('PERMISSION_EVENT', 'Permission Event'), ('SYSTEM_EVENT', 'System Event'), ('COMPLIANCE_EVENT', 'Compliance Event')], max_length=50)),
                ('aggregate_id', models.PositiveIntegerField()),
                ('aggregate_type', models.CharField(max_length=50)),
                ('event_data', models.JSONField()),
                ('event_version', models.PositiveIntegerField()),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('event_hash', models.CharField(max_length=64)),
                ('hash_prev_event', models.CharField(blank=True, max_length=64, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_eventstore',
                'ordering': ['aggregate_id', 'event_version'],
                'indexes': [models.Index(fields=['aggregate_id', 'event_version'], name='idx_evstore_agg_version'), models.Index(fields=['event_type', 'occurred_at'], name='core_events_event_t_ddc821_idx')],
            },
        ),
        migrations.CreateModel(
            name='BalanceCache',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_cache_obj', to='core.group')),
            ],
            options={
                'db_table': 'core_balancecache',
                'constraints': [models.CheckConstraint(condition=models.Q(('balance__gte', 0)), name='positive_balance_cache')],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VIEW', 'View'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout')], max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('object_id', models.PositiveIntegerField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('before_value', models.JSONField(blank=True, null=True)),
                ('after_value', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_hash', models.CharField(blank=True, max_length=64)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='core.group')),
            ],
            options={
                'db_table': 'core_auditlog',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['group', 'timestamp'], name='idx_auditlog_group_timestamp'), models.Index(fields=['user', 'timestamp'], name='idx_auditlog_user_timestamp'), models.Index(fields=['event_type', 'timestamp'], name='core_auditl_event_t_9f3ffc_idx')],
            },
        ),
        migrations.CreateModel(
            name='DebitEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('MEMBER_LOANS_RECEIVABLE', 'Member Loans Receivable'), ('EXPENSES', 'Expenses'), ('ADMINISTRATIVE', 'Administrative'), ('MEETING', 'Meeting'), ('EMERGENCY', 'Emergency'), ('PENALTIES', 'Penalties')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='debit_entry', to='core.ledgerentry')),
            ],
            options={
                'db_table': 'core_debitentry',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_debit_amount')],
            },
        ),
        migrations.CreateModel(
            name='CreditEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('account', models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank'), ('MEMBER_CONTRIBUTIONS', 'Member Contributions'), ('MEMBER_LOANS_PAYABLE', 'Member Loans Payable'), ('GROUP_EQUITY', 'Group Equity'), ('INVESTMENT_INTEREST', 'Investment Interest'), ('INVESTMENT_DIVIDEND', 'Investment Dividend'), ('BANK_INTEREST', 'Bank Interest'), ('OTHER_INCOME', 'Other Income')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ledger_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_entry', to='core.ledgerentry')),
            ],
            options={
                'db_table': 'core_creditentry',
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_credit_amount')],
            },
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['user', 'group'], name='core_memb_user_grp_active'),
        ),
        migrations.AddIndex(
            model_name='membership',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['group', 'role'], name='core_memb_grp_role_active'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'group'), name='unique_active_membership'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['group', 'occurred_at', 'amount'], name='idx_ledger_group_date_amount'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['member', 'group', 'occurred_at'], name='idx_ledger_member_group'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['transaction_id'], name='idx_ledger_transaction_id'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='positive_amount'),
        ),
        migrations.AddIndex(
            model_name='transactionhash',
            index=models.Index(fields=['hash_prev_tx'], name='idx_transaction_hash_prev'),
        ),
    ]
